name: Lint SQL files
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install Python dependencies
      run: pip install sqlfluff
    - name: Run linter
      run: |
        sqlfluff lint --dialect postgres .
