name: Test Query 01
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    # Use the postgis image to start a postgres service
    #
    # See the following links for more information:
    # https://hub.docker.com/_/postgis
    # https://docs.github.com/en/actions/guides/about-service-containers
    # https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
    services:
      postgres:
        # Use the following image to cut down on build time.
        # image: ghcr.io/${{ github.repository }}-database
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install JS dependencies
      run: |
        npm install
        npm install -g dotenv-cli
    - name: Install GDAL (for ogr2ogr)
      run: sudo apt install gdal-bin -y
    - name: Initialize DB connection variables
      run: cp .env.template .env
    - name: Load initial data
      run: dotenv __scripts__/load_data.sh
    - name: Apply database customizations
      run: dotenv __script__/apply_customizations.sh
    - name: Run tests
      run: |
        npm test __tests__/test_query01.js
