name: Test Query 02
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    # Use the postgis image to start a postgres service
    #
    # See the following links for more information:
    # https://hub.docker.com/_/postgis
    # https://docs.github.com/en/actions/guides/about-service-containers
    # https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
    services:
      postgres:
        # Use the following image to cut down on build time.
        # image: ghcr.io/${{ github.repository }}-database
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install data loading dependencies
      run: |
        sudo add-apt-repository ppa:ubuntugis/ppa
        sudo apt-get update
        sudo apt-get install -y curl unzip gdal-bin postgresql-client
    - name: Load data
      run: __scripts__/load_data.sh
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install JS dependencies
      run: npm install
    - name: Run tests
      run: |
        npm test __tests__/test_query02.js
